# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09a73f6454ae05af0b2844c024155211ac1121a795d9380ceb903f0f486a507f29c210720fe2756a3b23e5a2733a97bcb6f739c3ba7887ddacad5c9825d7ac2a

test:
  secret_key_base: bb130af7dfd492d59ee58b3b27d2fc3fd9a315aedb8d44cabe03146225931f24bb6337703ee73b1b3f2eb1f809bfe39f6b30beee7856df6c94365548513d579c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
